/*
==========================
==== CONSTANTES REDUX ====
==========================
*/

export const GET_APP_LANGUAGE_LOADING = 'GET_APP_LANGUAGE_LOADING';
export const GET_APP_LANGUAGE_SUCCESS = 'GET_APP_LANGUAGE_SUCCESS';
export const SET_APP_LANGUAGE_LOADING = 'SET_APP_LANGUAGE_LOADING';
export const SET_APP_LANGUAGE_ERROR = 'SET_APP_LANGUAGE_ERROR';
export const SET_APP_LANGUAGE_SUCCESS = 'SET_APP_LANGUAGE_SUCCESS';

// USER
export const RESET_USER_SUCCESS = 'RESET_USER_SUCCESS';
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS';
export const AUTHENTICATE_USER_LOADING = 'AUTHENTICATE_USER_LOADING';
export const AUTHENTICATE_USER_ERROR = 'AUTHENTICATE_USER_ERROR';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_LOADING = 'LOGOUT_USER_LOADING';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';
export const CLEAR_USER_SUCCESS = 'CLEAR_USER_SUCCESS';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_LOADING = 'GET_USER_LOADING';
export const GET_USER_ERROR = 'GET_USER_ERROR';
export const GET_USER_KEY_SUCCESS = 'GET_USER_KEY_SUCCESS';
export const GET_USER_KEY_LOADING = 'GET_USER_KEY_LOADING';
export const GET_USER_KEY_ERROR = 'GET_USER_KEY_ERROR';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_LOADING = 'REGISTER_USER_LOADING';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_LOADING = 'UPDATE_USER_LOADING';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
export const UPDATE_USER_PWD_SUCCESS = 'UPDATE_USER_PWD_SUCCESS';
export const UPDATE_USER_PWD_LOADING = 'UPDATE_USER_PWD_LOADING';
export const UPDATE_USER_PWD_ERROR = 'UPDATE_USER_PWD_ERROR';
export const UPDATE_USER_AVATAR_SUCCESS = 'UPDATE_USER_AVATAR_SUCCESS';
export const UPDATE_USER_AVATAR_LOADING = 'UPDATE_USER_AVATAR_LOADING';
export const UPDATE_USER_AVATAR_ERROR = 'UPDATE_USER_AVATAR_ERROR';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const GET_LIST_CATEGORY_SUCCESS = 'GET_LIST_CATEGORY_SUCCESS';
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const FORGET_PASSWORD_LOADING = 'FORGET_PASSWORD_LOADING';
export const FORGET_PASSWORD_ERROR = 'FORGET_PASSWORD_ERROR';
export const UPLOAD_PHOTO_GALERY_SUCCESS = 'UPLOAD_PHOTO_GALERY_SUCCESS';
export const UPLOAD_PHOTO_GALERY_LOADING = 'UPLOAD_PHOTO_GALERY_LOADING';
export const UPLOAD_PHOTO_GALERY_ERROR = 'UPLOAD_PHOTO_GALERY_ERROR';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_LOADING = 'CHANGE_PASSWORD_LOADING';
export const UPDATE_LOCATION_SUCCESS = 'UPDATE_LOCATION_SUCCESS';
export const UPDATE_LOCATION_LOADING = 'UPDATE_LOCATION_LOADING';
export const UPDATE_LOCATION_ERROR = 'UPDATE_LOCATION_ERROR';

//NOTIFICATIONS
export const SEND_NEARBY_NOTIFICATIONS_LOADING =
  'SEND_NEARBY_NOTIFICATIONS_LOADING';
export const SEND_NEARBY_NOTIFICATIONS_ERROR =
  'SEND_NEARBY_NOTIFICATIONS_ERROR';
export const SEND_NEARBY_NOTIFICATIONS_SUCCESS =
  'SEND_NEARBY_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATION_LOADING = 'GET_NOTIFICATION_LOADING';
export const GET_NOTIFICATION_ERROR = 'GET_NOTIFICATION_ERROR';
export const GET_NOTIFICATION_SUCCESS = 'GET_NOTIFICATION_SUCCESS';
export const GET_ALL_NOTIFICATIONS_LOADING = 'GET_ALL_NOTIFICATIONS_LOADING';
export const GET_ALL_NOTIFICATIONS_ERROR = 'GET_ALL_NOTIFICATIONS_ERROR';
export const GET_ALL_NOTIFICATIONS_SUCCESS = 'GET_ALL_NOTIFICATIONS_SUCCESS';
export const SET_FIREBASE_TOKEN = 'SET_FIREBASE_TOKEN';

export const READ_NOTIFICATION_LOADING = 'READ_NOTIFICATION_LOADING';
export const READ_NOTIFICATION_SUCCESS = 'READ_NOTIFICATION_SUCCESS';
export const READ_NOTIFICATION_ERROR = 'READ_NOTIFICATION_ERROR';

export const DELETE_NOTIFICATION_LOADING = 'DELETE_NOTIFICATION_LOADING';
export const DELETE_NOTIFICATION_SUCCESS = 'DELETE_NOTIFICATION_SUCCESS';
export const DELETE_NOTIFICATION_ERROR = 'DELETE_NOTIFICATION_ERROR';

export const GET_NUMBER_NOTIFICATION_ERROR = 'GET_NUMBER_NOTIFICATION_ERROR';
export const GET_NUMBER_NOTIFICATION_SUCCESS =
  'GET_NUMBER_NOTIFICATION_SUCCESS';
export const GET_NUMBER_NOTIFICATION_LOADING =
  'GET_NUMBER_NOTIFICATION_LOADING';
export const UPDATE_NOTIFICATION_SETTINGS_LOADING =
  'UPDATE_NOTIFICATION_SETTINGS_LOADING';
export const UPDATE_NOTIFICATION_SETTINGS_ERROR =
  'UPDATE_NOTIFICATION_SETTINGS_ERROR';
export const UPDATE_NOTIFICATION_SETTINGS_SUCCESS =
  'UPDATE_NOTIFICATION_SETTINGS_SUCCESS';
export const GET_NOTIFICATION_SETTINGS_LOADING =
  'GET_NOTIFICATION_SETTINGS_LOADING';
export const GET_NOTIFICATION_SETTINGS_ERROR =
  'GET_NOTIFICATION_SETTINGS_ERROR';
export const GET_NOTIFICATION_SETTINGS_SUCCESS =
  'GET_NOTIFICATION_SETTINGS_SUCCESS';
export const READ_ALL_NOTIFICATIONS_LOADING = 'READ_ALL_NOTIFICATIONS_LOADING';
export const READ_ALL_NOTIFICATIONS_ERROR = 'READ_ALL_NOTIFICATIONS_ERROR';
export const READ_ALL_NOTIFICATIONS_SUCCESS = 'READ_ALL_NOTIFICATIONS_SUCCESS';

export const SET_THEME = 'SET_THEME';
export const GET_THEME = 'GET_THEME';

// USER_SCORES
export const GET_SCORES_LOADING = 'GET_SCORES_LOADING';
export const GET_SCORES_SUCCESS = 'GET_SCORES_SUCCESS';
export const GET_SCORES_ERROR = 'GET_SCORES_ERROR';
export const UPDATE_USER_SCORE_LOADING = 'UPDATE_USER_SCORE_LOADING';
export const UPDATE_USER_SCORE_ERROR = 'UPDATE_USER_SCORE_ERROR';
export const UPDATE_USER_SCORE_SUCCESS = 'UPDATE_USER_SCORE_SUCCESS';

// Variable to login as a guest

export const LOGIN_AS_GUEST = 'LOGIN_AS_GUEST';
export const LOGIN_AS_GUEST_ERROR = 'LOGIN_AS_GUEST_ERROR';
export const LOGIN_AS_GUEST_SUCCESS = 'LOGIN_AS_GUEST_SUCCESS';
export const LOGIN_AS_GUEST_LOADING = 'LOGIN_AS_GUEST_LOADING';

export const GET_CLUBS_LOADING = 'GET_CLUBS_LOADING';
export const GET_CLUBS_ERROR = 'GET_CLUBS_ERROR';
export const GET_CLUBS_SUCCESS = 'GET_CLUBS_SUCCESS';

export const GET_CLUB_LOADING = 'GET_CLUB_LOADING';
export const GET_CLUB_ERROR = 'GET_CLUB_ERROR';
export const GET_CLUB_SUCCESS = 'GET_CLUB_SUCCESS';

export const DELETE_SCORE_CARD_SUCCESS = 'DELETE_SCORE_CARD_SUCCESS';
export const DELETE_SCORE_CARD_LOADING = 'DELETE_SCORE_CARD_LOADING';
export const DELETE_SCORE_CARD_ERROR = 'DELETE_SCORE_CARD_ERROR';

export const CREATE_SCORE_CARD_LOADING = 'CREATE_SCORE_CARD_LOADING';
export const CREATE_SCORE_CARD_ERROR = 'CREATE_SCORE_CARD_ERROR';
export const CREATE_SCORE_CARD_SUCCESS = 'CREATE_SCORE_CARD_SUCCESS';
export const CREATE_MULTIPLAYER_SCORE_CARD_SUCCESS = 'CREATE_MULTIPLAYER_SCORE_CARD_SUCCESS';


export const REDEEMING_CODE_LOADING = 'REDEEMING_CODE_LOADING';
export const REDEEMING_CODE_ERROR = 'REDEEMING_CODE_ERROR';
export const REDEEMING_CODE_SUCCESS = 'REDEEMING_CODE_SUCCESS';

export const GET_SCORE_CARD_LOADING = 'GET_SCORE_CARD_LOADING';
export const GET_SCORE_CARD_ERROR = 'GET_SCORE_CARD_ERROR';
export const GET_SCORE_CARD_SUCCESS = 'GET_SCORE_CARD_SUCCESS';

export const GET_SCORE_CARD_LIST_LOADING = 'GET_SCORE_CARD_LIST_LOADING';
export const GET_SCORE_CARD_LIST_ERROR = 'GET_SCORE_CARD_LIST_ERROR';
export const GET_SCORE_CARD_LIST_SUCCESS = 'GET_SCORE_CARD_LIST_SUCCESS';

export const UPDATE_SCORE_CARD_LOADING = 'UPDATE_SCORE_CARD_LOADING';
export const UPDATE_SCORE_CARD_ERROR = 'UPDATE_SCORE_CARD_ERROR';
export const UPDATE_SCORE_CARD_SUCCESS = 'UPDATE_SCORE_CARD_SUCCESS';

export const GET_MYSPOTS_LOADING = 'GET_MYSPOTS_LOADING';
export const GET_MYSPOTS_ERROR = 'GET_MYSPOTS_ERROR';
export const GET_MYSPOTS_SUCCESS = 'GET_MYSPOTS_SUCCESS';

export const VALIDATE_QRCODE_LOADING = 'VALIDATE_QRCODE_LOADING';
export const VALIDATE_QRCODE_ERROR = 'VALIDATE_QRCODE_ERROR';
export const VALIDATE_QRCODE_SUCCESS = 'VALIDATE_QRCODE_SUCCESS';

export const SET_LOCATION = 'SET_LOCATION';

export const SET_REFRESH_CLUB_DETAILS = 'SET_REFRESH_CLUB_DETAILS';

export const SET_RESET_CLUB = 'SET_RESET_CLUB';

// SCORES LIST
export const SET_SCORES_LIST = 'SET_SCORES_LIST';

export const REFRESH_COLLECTION_LIST = 'REFRESH_COLLECTION_LIST';

export const APPLE_APP_ID = '1469038816'; //TODO: Change after getting the apple_app_id
export const GOOGLE_PACKAGE_NAME = 'com.mruFood.mobileapp';

export const DARK_THEME = 'DARK_THEME';
export const LIGHT_THEME = 'LIGHT_THEME';
export const DARK_COLORS = {
  transparent: 'rgba(0,0,0,0)',
  // Example colors:
  white: '#ffffff',
  text: '#53CD95',
  primary: '#7FF2AA',
  textColor: '#171717',
  success: '#28a745',
  error: '#dc3545',
  icons: '#171717',
  background: '#171717',
  backgroundColor: '#53CD95',
  secondaryTextColor: 'black',
  greyText: '#7B7878',
  headerTintColor: '#fff',
  avatarBorder: '#171717',
  headerBackground: '#171717',
  accessoryBackground: '#171717',
};

export const LIGHT_COLORS = {
  transparent: 'rgba(0,0,0,0)',
  // Example colors:
  white: '#ffffff',
  text: '#212529',
  primary: '#7FF2AA',
  textColor: 'white',
  success: '#28a745',
  error: '#dc3545',
  icons: '#fff',
  background: '#e4e4e4',
  backgroundColor: '#53CD95',
  secondaryTextColor: 'black',
  //greyText: '#7B7878',
  greyText: '#7B7878',
  headerTintColor: '#fff',
  avatarBorder: '#fff',
  headerBackground: '#fff',
  accessoryBackground: '#fff',
};

export const GOOGLE_WEB_CLIENT_ID =
  '491031556886-vqlcohe2j4rcjr4383d04960is2q6vac.apps.googleusercontent.com';

export const MAP_STYLE = [
  {
    featureType: 'administrative.land_parcel',
    elementType: 'labels',
    stylers: [
      {
        visibility: 'off',
      },
    ],
  },
  {
    featureType: 'poi',
    stylers: [
      {
        visibility: 'off',
      },
    ],
  },
  {
    featureType: 'poi.business',
    stylers: [
      {
        visibility: 'off',
      },
    ],
  },
  {
    featureType: 'road',
    elementType: 'labels.icon',
    stylers: [
      {
        visibility: 'off',
      },
    ],
  },
  {
    featureType: 'road.local',
    elementType: 'labels',
    stylers: [
      {
        visibility: 'off',
      },
    ],
  },
  {
    featureType: 'transit',
    stylers: [
      {
        visibility: 'off',
      },
    ],
  },
];

export const SEND_BUG_ERROR = 'SEND_BUG_ERROR';
export const SEND_BUG_LOADING = 'SEND_BUG_LOADING';
export const SEND_BUG_SUCCESS = 'SEND_BUG_SUCCESS';

// TEES
export const GET_TEES_LOADING = 'GET_TEES_LOADIN';
export const GET_TEES_ERROR = 'GET_TEES_SUCCESS';
export const GET_TEES_SUCCESS = 'GET_TEES_ERROR';

export const GET_BALL_ERROR = 'GET_BALL_ERROR';
export const GET_BALL_LOADING = 'GET_BALL_LOADING';
export const GET_BALL_SUCCESS = 'GET_BALL_SUCCESS';

export const UPDATE_NOTIFICATION_COUNT = 'UPDATE_NOTIFICATION_COUNT';
export const SET_SHOW_ALERT_MODAL = 'SET_SHOW_ALERT_MODAL';

export const GET_MARKERS_SUCCESS = 'GET_MARKERS_SUCCESS';
export const GET_MARKERS_ERROR = 'GET_MARKERS_ERROR';
export const GET_MARKERS_LOADING = 'GET_MARKERS_LOADING';

export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_LOADING = 'CREATE_POST_LOADING';

export const UPDATE_SPOT_COUNT = 'UPDATE_SPOT_COUNT';

