require_relative "../node_modules/react-native/scripts/react_native_pods"
require_relative "../node_modules/@react-native-community/cli-platform-ios/native_modules"

platform :ios, "10.0"

target "mruFoodApp" do
  config = use_native_modules!

  # use_react_native!(:path => config["reactNativePath"])
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false,
  )

  pod "RNVectorIcons", path: "../node_modules/react-native-vector-icons"
  pod "react-native-camera", path: "../node_modules/react-native-camera", subspecs: [
                               "BarcodeDetectorMLKit",
                             ]
  pod "Firebase/Core"
  pod "RNFBApp", :path => "../node_modules/@react-native-firebase/app"

  pod "react-native-image-picker", :path => "../node_modules/react-native-image-picker"

  pod "lottie-react-native", :path => "../node_modules/lottie-react-native"

  target "mruFoodAppTests" do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.p
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

# Enables Flipper.
#
# Note that if you have use_frameworks! enabled, Flipper will not work and
# you should disable the next line.
use_flipper!()

post_install do |installer|
  react_native_post_install(installer)
  installer.pods_project.targets.each do |target|
    if target.name == "react-native-google-maps"
      target.build_configurations.each do |config|
        config.build_settings["CLANG_ENABLE_MODULES"] = "No"
      end
    end
  end
end
